openapi: 3.0.3
info:
  title: Hei Wallet API
  version: 1.0.0
  description: STD22052 - STD22069
servers:
  - url: https://hei.wallet.api.com
paths:
  /ping:
    get:
      tags:
        - Security
      summary: pong
      operationId: ping
      responses:
        200:
          $ref: '#/components/responses/Ping200'
        400:
          $ref: "#/components/responses/400"
        403:
          $ref: "#/components/responses/403"
        500:
          $ref: "#/components/responses/500"
components:
  schemas:
    Currency:
      type: object
      properrties:
        id:
          type: string
        currency_name:
          type: string
        code:
          $ref: '#/components/schemas/Code'
        symbole:
          $ref: '#/components/schemas/Symbole'
        exchange_rate:
          type: float
        updated_at:
          type: string
          format: date-time
    Code:
      type: string
      enum:
        - USD
        - EUR
        - MGA
    Symbole:
      type: string
      enum:
        - $
        - €
        - Ar
    ResponseBody:
      type: object
      properties:
        code:
          type: integer
          example: 200
        message:
          type: string
          example: OK
    PingBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
      example:
        status:
          code: 200 
          message: pong 
        body: null 
    BadRequestBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
      example:
        status:
          code: 400
          message: BAD REQUEST
        body: null 
    ForbiddenBody:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
      example:
        status:
          code: 403
          message: FORBIDDEN
        body: null 
    InternalServerError:
      allOf:
        - $ref: '#/components/schemas/ResponseBody'
      example:
        status:
          code: 500 
          message: INTERNAL SERVER ERROR 
        body: null
  responses:
    Ping200:
      description: pong
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PingBody'
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestBody'
    403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ForbiddenBody'
    500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerError'